-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dim.foe
(
    foe_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    foe_name text COLLATE pg_catalog."default",
    CONSTRAINT foe_pkey PRIMARY KEY (foe_code)
);

CREATE TABLE IF NOT EXISTS dim.funding_cluster
(
    cluster_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cluster_name text COLLATE pg_catalog."default",
    CONSTRAINT funding_cluster_pkey PRIMARY KEY (cluster_code)
);

CREATE TABLE IF NOT EXISTS fact.enrolment_2024
(
    enrol_id bigserial NOT NULL,
    foe_code character varying(10) COLLATE pg_catalog."default",
    eftsl numeric(6, 3),
    student_contribution numeric(12, 2),
    commonwealth_contribution numeric(12, 2),
    tuition_amount numeric(12, 2),
    enrol_unit integer,
    CONSTRAINT enrolment_2024_pkey PRIMARY KEY (enrol_id)
);

CREATE TABLE IF NOT EXISTS "raw".csp_allocation_2024
(
    row_id bigserial NOT NULL,
    broad_discipline_foe text COLLATE pg_catalog."default",
    narrow_discipline_foe text COLLATE pg_catalog."default",
    detailed_discipline_foe text COLLATE pg_catalog."default",
    funding_cluster text COLLATE pg_catalog."default",
    max_student_contribution_2024 text COLLATE pg_catalog."default",
    commonwealth_contribution_2024 text COLLATE pg_catalog."default",
    foe_code character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT csp_allocation_2024_pkey PRIMARY KEY (row_id)
);

COMMENT ON TABLE "raw".csp_allocation_2024
    IS 'Raw CSP allocation (2024), as published by government';

CREATE TABLE IF NOT EXISTS "raw".student_enrolments_2024
(
    row_id bigserial NOT NULL,
    course_type_broad_name text COLLATE pg_catalog."default",
    funding_group_name text COLLATE pg_catalog."default",
    unit_level text COLLATE pg_catalog."default",
    unit_primary_foe_code text COLLATE pg_catalog."default",
    unit_primary_foe_detailed_name text COLLATE pg_catalog."default",
    unit_primary_foe_narrow_name text COLLATE pg_catalog."default",
    unit_primary_foe_broad_name text COLLATE pg_catalog."default",
    eftsl_2024 numeric(6, 3),
    CONSTRAINT student_enrolments_2024_pkey PRIMARY KEY (row_id)
);

ALTER TABLE IF EXISTS fact.enrolment_2024
    ADD CONSTRAINT enrolment_2024_foe_code_fkey FOREIGN KEY (foe_code)
    REFERENCES dim.foe (foe_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;